name: my-env-name
channels:
  - conda-forge
  - defaults
dependencies:
  - glpk
  - ipopt
  - pip
  - pip:
      - numpy
      - matplotlib
      - scipy
      - sympy
      - pandas
      - pyomo
      